DEVPROD-3776 Add fields to Task in evergreen.py
evergreen-ci/evergreen.py pull request #169
Opened 2024-04-15 17:21 UTC by namazgurbanovmdb

2024-04-15 17:23 UTC, rongodb requested changes
need to update the readme and the project.toml as well.

2024-04-15 21:11 UTC, gmishkin reviewed
I don't see these fields on https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage#tag/tasks/paths/~1tasks~1%7Btask_id%7D/get

Aren't these fields only added by our flaky detection based on the Trino data? They are not part of the Evergreen REST API task object.

If we want a single class to store this data we need to inherit the evergreen task object and augment it, or make a wrapper class that adds the Trino fields and overrides `__call__` or something to get other fields from the evergreen.py task object.

2024-04-18 20:30 UTC, namazgurbanovmdb commented on src/evergreen/task.py
> +    end_time = evg_datetime_attrib("end_time")
Its defined under test, not task.

2024-04-18 20:37 UTC, gmishkin commented on src/evergreen/task.py
> +    end_time = evg_datetime_attrib("end_time")
Ok, but then you shouldn't add it here, right?

2024-04-18 20:41 UTC, rongodb approved these changes

2024-04-18 20:43 UTC, namazgurbanovmdb commented on src/evergreen/task.py
> +    end_time = evg_datetime_attrib("end_time")
You are right. It already exists under Test. Deleting this PR

2024-04-18 20:44 UTC, closed without merging