Add endpoints for updating patches & tasks
evergreen-ci/evergreen.py pull request #64
Opened 2020-10-28 16:35 UTC by savannaendicott

This pull requests adds coverage for the following endpoints to evergreen.py: 
- POST [/tasks/{task_id}/restart](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#restart-a-task)
- POST [/tasks/{task_id}/abort](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#abort-a-task)
- PATCH [/tasks/{task_id}](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#change-a-tasks-execution-status)
- POST [/patches/{patch_id}/configure](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#configureschedule-a-patch)

Refactoring included:
- refactored `_call_api` to be used for all requests -- instead of only GET. Another option would be to rename the method to reflect that it's only used for GET and add separate methods for POST & PATCH, however this would involve the same amount of line changes.

2020-10-28 17:12 UTC, dbradf requested changes
Could you update the version in `pyproject.toml` and add a description of this change in `CHANGELOG.md`?

2020-10-28 17:12 UTC, dbradf commented on src/evergreen/api.py
> +        with value of a list of task names to configure for specified variant. See the documentation for more details
Since this param string extends to multiple lines, our docs parser expects the lines after the first to be indented.

2020-10-28 17:37 UTC, dbradf commented
Let me know when this is ready and I can merge it for you. After it gets merged, it should auto-deploy to pypi within a few minutes.

2020-10-29 12:47 UTC, savannaendicott commented
> Let me know when this is ready and I can merge it for you. After it gets merged, it should auto-deploy to pypi within a few minutes.

Hi @dbradf I have made a minor additional change, I had added "variants" as an optional parameter for configuring patches but it is required by the endpoint. This is now fixed, and **ready to merge**.

2020-10-29 12:48 UTC, dbradf commented
evergreen merge

2020-10-29 12:52 UTC, merged